version: "3"

services:
    server:
        image: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - ./config:/etc/nginx
        networks:
            -  nginx-net

networks:
    nginx-net:
        external: true